#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run format

if [ -z "$(git status --porcelain)" ]; then
  echo "All fine"
else
  echo "Some files were formatted..."
  git commit -am "fix: format" --no-verify;
fi
